# Generated by Django 2.0.7 on 2018-08-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producr',
            new_name='Product',
        ),
    ]
